version: 1
formatters:
  simple:
    format: '[%(asctime)s]: %(message)s'
    datefmt: '%I:%M:%S'
handlers:
  file:
    class: logging.FileHandler
    filename: training.log
    formatter: simple
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
root:
  handlers: [file]

disable_existing_loggers: false